source 'https://github.com/CocoaPods/Specs.git'

def import_pods
    pod "NetWorker", :path => "../"
    pod "NetWorker/RAC", :path => "../"
    pod "NetWorker/Logger", :path => "../"
end

target 'NetWorker', :exclusive => true do
  import_pods
end

target 'Tests', :exclusive => true do
  import_pods

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
